config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    member do
      patch :complete
    end
  end
 root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  # creating an association between the user and tasks
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # creating an association between the user and tasks
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    if user_signed_in?
      @tasks = Task.where(:user_id => current_user.id).order("created_at DESC")
  end
end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed_at, Time.now)
    redirect_to root_path, notice: "Task successfully completed!"
  end

private

  def task_params
    params.require(:task).permit(:title, :description)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_static_landing_page.html.erb
<div class="jumbotron">
  <h1>Welcome to HoneyDew</h1>
  <p>Dew you, Boo Boo!</p>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
  <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Honeydew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "HoneyDew", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "New Task", new_task_path, class: "navbar-text navbar-link navbar-right" %>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title, label: "Task" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<!-- corresponds to the update and edit actions in tasks_controller.erb -->
<div class="col-md-6 col-md-offset-3">

<h1>Edit DewList Task</h1>

<!-- rendering partial form from _form.html.erb -->
<%= render "form" %>
<%= link_to "Back", root_path %>
</div>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @tasks.each do |task| %>
				<% if task.completed? %>

					<div class="row task">
						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="task-title"><strike><%= link_to task.title, task %></strike></h2>
							<p style="opacity: 0.5;" class="task-desc task-sub-title"><%= task.description %></p>
							<p style="opacity: 0.5;" class="time-ago task-sub-title">Completed <%= time_ago_in_words(task.completed_at) %> ago</p>
						</div>

						<div class="col-md-2">
							<p><%= link_to complete_task_path(task), method: :patch do %></p>
								<i class="fa fa-lg fa-check"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-lg fa-trash"></i>
							<% end %>
						</div>
					</div>

				<% else %>
					<div class="row task">
						<div class="col-md-8">
							<h2 class="task-title"><%= link_to task.title, task %></h2>
							<p class="task-sub-title task-desc"><%= task.description %></p>
							<p class="time-ago task-sub-title">Created <%= time_ago_in_words(task.created_at) %> ago</p>
						</div>

						<div class="col-md-2">
							<p><%= link_to complete_task_path(task), method: :patch do %></p>
								<i class="fa fa-lf fa-check"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-lg fa-trash"></i>
							<% end %>
						</div>
					</div>
				<% end %>
		<% end %>
	</div>
<% else %>
	<%= render 'layouts/static_landing_page' %>
<% end %>

app/views/tasks/new.html.erb
<!-- corresponds to new action in the tasks_controller.rb -->
<div class="col-md-6 col-md-offset-3">

<h1>Dew New Task</h1>
<!-- this is the view for a user to create a new DewList task -->
<!-- rendering from the partial for at _form.html.erb -->
<%= render 'form' %>
<%= link_to "Back", root_path %>

</div>

app/views/tasks/show.html.erb
<!-- corresponding view to the show action in tasks_controller.rb -->
<div class="col-md-6 col-md-offset-3">

<h2><%= @task.title %></h2>
<p><%= @task.description %></p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_task_path(@task) %>
</div>